[package]
name = "testing-turmoil"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
mockall = "0.11.3"
mockall_double = "0.3.0"

[dev-dependencies]
mockall = "0.11.3"
mockall_double = "0.3.0"
